#!/usr/bin/env bash

# javascript (nvm, node, bun)
yarn global remove eslint typescript-language-server typescript ts-node pm2
rm -rf "$HOME/.nvm"
rm -rf "$HOME/.bun"

# core
sudo apt -y purge curl htop lsof xclip autorandr build-essential ninja-build fd-find rofi ripgrep stow

# zsh
sudo apt -y purge zsh
rm -rf "$HOME/.oh-my-zsh"

# vim
sudo apt -y purge vim

# nvim
rm -f "$HOME/nvim.appimage"
sudo rm -f /usr/local/bin/nvim
rm -rf "$HOME/.local/share/nvim"

# terminal
sudo apt -y purge kitty imagemagick

# window manager
sudo apt -y purge i3 numlockx volumeicon-alsa maim xdotool

# apps
sudo snap remove code
sudo apt -y purge google-chrome-stable

# wallpapers
sudo apt -y purge nitrogen

# productivity
sudo apt -y purge fzf
rm -rf "$HOME/.config/fzf"

# dotfiles
rm -rf "$HOME/.dotfiles"

sudo apt -y autoremove
