- name: Install VSCode
  become: true
  shell: "snap install --classic code"
  tags:
    - install
    - apps
    - vscode

- name: Install Chrome
  become: true
  shell: "wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && apt install ./google-chrome-stable_current_amd64.deb && rm -f ./google-chrome-stable_current_amd64.deb"
  tags:
    - install
    - apps
    - chrome
