- name: Install System Packages
  become: true
  apt:
    name: [ "curl", "htop", "lsof", "xclip", "autorandr", "build-essential", "ninja-build", "fd-find", "rofi", "ripgrep", "unzip", "snapd" ]
  tags:
    - install
    - core

- name: Ensure ~/.local/bin exists
  file:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin"
    state: directory
    mode: '0755'
  tags:
    - install
    - core

- name: Link fd-find
  become: true
  shell: "rm -f {{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin/fd && ln -s $(which fdfind) {{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin/fd"
  tags:
    - install
    - core

- name: Install Russian Language
  become: true
  shell: "apt -y install $(check-language-support -l ru)"
  tags:
    - install
    - core
    - language

    