- name: Install System Packages
  become: true
  apt:
    name: [ "curl", "htop", "lsof", "i3", "build-essential", "ninja-build" ]
  tags:
    - install
    - core
    
- name: dconf i3
  shell: update-alternatives --install /usr/bin/x-session-manager x-session-manager /usr/bin/i3 60 
  tags:
    - install
    - core
