- name: Install System Packages
  become: true
  apt:
    name: [ "curl", "htop", "lsof", "build-essential", "ninja-build", "fd-find", "rofi" ]
  tags:
    - install
    - core

- name: Link fd-find
  become: true
  shell: ln -s $(which fdfind) ~/.local/bin/fd
  tags:
    - install
    - cor