- name: Install System Packages
  become: true
  apt:
    name: [ "curl", "htop", "lsof", "build-essential", "ninja-build", "fd-find", "rofi" ]
  tags:
    - install
    - core

- name: Link fd-find
  become: true
  shell: "rm -f {{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin/fd && ln -s $(which fdfind) {{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin/fd"
  tags:
    - install
    - core

- name: Install Russian Language
  become: true
  shell: "apt -y install $(check-language-support -l ru)"
  tags:
    - install
    - core
    - language

    