- name: Install Docker dependencies
  become: true
  apt:
    name: [ "ca-certificates", "gnupg", "lsb-release" ]
  tags:
    - install
    - docker

- name: Add Docker GPG key
  become: true
  shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg
  tags:
    - install
    - docker

- name: Add Docker apt repository
  become: true
  shell: |
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update
  args:
    creates: /etc/apt/sources.list.d/docker.list
  tags:
    - install
    - docker

- name: Install Docker Engine
  become: true
  apt:
    name: [ "docker-ce", "docker-ce-cli", "containerd.io", "docker-buildx-plugin", "docker-compose-plugin" ]
  tags:
    - install
    - docker

- name: Install dtop
  shell: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/amir20/dtop/releases/latest/download/dtop-installer.sh | sh
  args:
    executable: /bin/bash
  tags:
    - install
    - docker

- name: Add user to docker group
  become: true
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: true
  tags:
    - install
    - docker
