- name: Installing stow
  become: true
  apt: 
    name: [ 'stow' ]
  tags:
    - install
    - dotfiles
    - stow

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/Escral/.dotfiles.git'
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow

- name: Switch .dotfiles remote to SSH
  shell: git -C {{ lookup('ansible.builtin.env', 'HOME') }}/.dotfiles remote set-url origin git@github.com:Escral/.dotfiles.git
  tags:
    - install
    - dotfiles
    - stow
    
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./ubuntu
  tags:
    - install
    - dotfiles
    - stow
