- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"
  when: git_email is defined and git_email != ''
  tags:
    - git-personal

- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "{{ git_name }}"
  when: git_name is defined and git_name != ''
  tags:
    - git-personal
