- name: Install fnm
  shell: |
    curl -fsSL https://fnm.vercel.app/install | bash
  args:
    creates: "{{ lookup('env', 'HOME') }}/.local/share/fnm/fnm"
  tags:
    - install
    - node

- name: Install Node.js
  shell: |
    export PATH="{{ lookup('env', 'HOME') }}/.local/share/fnm:$PATH"
    eval "$(fnm env)"
    fnm install v22
    fnm default v22
  args:
    creates: "{{ lookup('env', 'HOME') }}/.local/share/fnm/aliases/default"
  tags:
    - install
    - node

- name: Install Bun
  shell: |
    curl -fsSL https://bun.sh/install | bash
  args:
    creates: "{{ lookup('env', 'HOME') }}/.bun/bin/bun"
  tags:
    - install
    - node
    - bun
