- name: Install nvm
  become: true
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | zsh
    . ~/.zshrc
  tags:
    - install
    - node

- name: Install Node.js
  become: true
  shell: |
    . {{ lookup('ansible.builtin.env', 'HOME') }}/.nvm/nvm.sh && nvm install v16
  tags:
    - install
    - node

- name: Install NPM
  become: true
  apt: 
    name: npm
  tags:
    - install
    - node
