- name: Install Yarn
  shell: |
    export PATH="{{ lookup('ansible.builtin.env', 'HOME') }}/.local/share/fnm:$PATH"
    eval "$(fnm env)"
    fnm use default
    npm install -g yarn
  args:
    creates: "{{ lookup('env', 'HOME') }}/.local/share/fnm/aliases/default/installation/bin/yarn"
  tags:
    - install
    - node

- name: Install global npm packages
  shell: |
    export PATH="{{ lookup('ansible.builtin.env', 'HOME') }}/.local/share/fnm:$PATH"
    eval "$(fnm env)"
    fnm use default
    yarn global add eslint typescript-language-server typescript ts-node pm2
  tags:
    - install
    - node
    
