- name: Get lazy.nvim
  ansible.builtin.git:
    repo: 'https://github.com/folke/lazy.nvim.git'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/lazy/lazy.nvim"
    version: stable
  tags:
    - install
    - neovim

- name: Add Neovim PPA
  become: true
  shell: |
    add-apt-repository -y ppa:neovim-ppa/unstable
    apt-get update
  args:
    creates: /etc/apt/sources.list.d/neovim-ppa-ubuntu-unstable-*.list
  tags:
    - install
    - neovim

- name: Install Neovim and dependencies
  become: true
  apt:
    name:
      - neovim
      - luarocks
      - libsqlite3-dev
  tags:
    - install
    - neovim

