- name: Get Packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
    - install
    - neovim

- name: Install Neovim
  become: true
  shell: |
    curl -Lo {{ lookup('env', 'HOME') }}/nvim.appimage https://github.com/neovim/neovim/releases/download/stable/nvim.appimage && \
    chmod u+x {{ lookup('env', 'HOME') }}/nvim.appimage && \
    sudo ln -s {{ lookup('env', 'HOME') }}/nvim.appimage /usr/local/bin/nvim
  tags:
    - install
    - neovim