- name: Install Kitty Terminal
  apt: 
    name: [ "kitty" ]
  tags:
    - terminal
    - kitty

- name: Make Kitty default terminal
  become: true
  shell: "update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator `which kitty` 50"
  tags:
    - terminal
    - kitty