- name: Install Nitrogen
  become: true
  apt: 
    name: nitrogen
  tags:
    - install
    - nitrogen

- name: Download Wallpapers
  ansible.builtin.git:
    repo: 'https://github.com/Escral/wallpapers.git'
    dest: "{{ personal }}/wallpapers"
  tags:
    - install
    - personal-project
    - wallpapers

- name: Switch wallpapers remote to SSH
  shell: git -C {{ personal }}/wallpapers remote set-url origin git@github.com:Escral/wallpapers.git
  tags:
    - install
    - personal-project
    - wallpapers
