- name: Install System Packages
  become: true
  apt:
    name: [ "i3", "rofi", "numlockx", "volumeicon-alsa", "maim", "xdotool" ]
  tags:
    - install
    - wm

- name: Install dunst and papirus-icon-theme
  become: true
  apt:
    name: [ "dunst", "papirus-icon-theme", "breeze-icon-theme" ]
  tags:
    - install
    - wm
    - dunst

#- name: dconf i3
#  shell: update-alternatives --install /usr/bin/x-session-manager x-session-manager /#usr/bin/i3 60 
#  tags:
#    - install
#    - wm