- name: Install System Packages
  become: true
  apt:
    name: [ "i3" ]
  tags:
    - install
    - wm

#- name: dconf i3
#  shell: update-alternatives --install /usr/bin/x-session-manager x-session-manager /#usr/bin/i3 60 
#  tags:
#    - install
#    - wm

- name: Configure X
  shell: 'xset r rate 400'
  tags:
    - install
    - wm

- name: Install rofi
  apt:
    name: [ "rofi" ]
  tags:
    - install
    - wm

- name: Install volumeicon
  apt:
    name: [ "volumeicon-alsa" ]
  tags:
    - install
    - wm
    - volume
