- name: Install System Packages
  become: true
  apt:
    name: [ "i3" ]
  tags:
    - install
    - wm

#- name: dconf i3
#  shell: update-alternatives --install /usr/bin/x-session-manager x-session-manager /#usr/bin/i3 60 
#  tags:
#    - install
#    - wm
